apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: mycon-1
      image: mary511/javaproimage:javadevenv
      ports:
        - containerPort: 8080
          protocol: TCP
  initContainers:
    - name: testing-purpose1
      image: alpine
      command:
        -  "sleep"
        -  "5s"
    - name: testing-purpose2
      image: alpine
      command:
        -  "sleep"
        -  "5s"

     